dist: xenial
language: go

matrix:
  include:
  - go: 1.8.7
  - go: 1.9.7
  - go: 1.10.8
  - go: 1.11.11
  - go: 1.12.6

install:
  - # Do nothing.

script:
  - go get -t -v ./... github.com/mattn/goveralls
  - go test -v -short -race ./...
  - diff -u <(echo -n) <(gofmt -d -s .)

after_success:
  - goveralls -service=travis-ci
