language: go

matrix:
  include:
  - go: 1.7.6
  - go: 1.8.5
  - go: 1.9.6
  - go: 1.10.2

install:
  - # Do nothing.

script:
  - go get -t -v ./... github.com/mattn/goveralls
  - go test -v -short -race ./...
  - diff -u <(echo -n) <(gofmt -d -s .)
  - go vet ./...

after_success:
  - go test -short -cover -covermode=count -coverprofile=$dir/profile.out $dir > all.out
  - goveralls -coverprofile=all.out -service=travis-ci
